### PR TITLE
Add spermy operator

### PR DESCRIPTION
**Pull request by mifix**
Sources e.g. https://twitter.com/mariocarrion/status/629683116362309632 or http://stackoverflow.com/questions/4292905/what-is-the-difference-between-and-when-specifying-rubygem-in-gemfile

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
Hi Christian, thanks for the Pull Request! But I think this is not appropriate https://github.com/rubygems/rubygems/pull/124. :bow:

**Comment by unused** [comment]
+1

**Comment by fuadsaud** [comment]
It's deprecated as official language, but wouldn't account it as inappropriate 😕

:+1: for it

**Comment by JuanitoFatas** [comment]
> It's deprecated as official language, but wouldn't account it as inappropriate

You're right!

@mifix @unused @fuadsaud @jimmynguyc added in ab2adb9.

**Comment by jimmynguyc** [comment]
:+1:

**Pull request closed without merging**
